import type { Site } from "../Models/Site";
import type { Plant } from "../Models/Plant";
import type { ClosedProtocol } from "../Models/ClosedProtocol";

export const sites: Site[] = [
  {
    id: "site-1",
    name: "Berlin Manufacturing Hub",
    abbreviationName: "BMH",
    zip: "10115",
    address: "Industriestraße 12",
    city: "Berlin",
    country: "Germany",
  },
  {
    id: "site-2",
    name: "Munich Engineering Center",
    abbreviationName: "MEC",
    zip: "80331",
    address: "Technikweg 5",
    city: "Munich",
    country: "Germany",
  },
  {
    id: "site-3",
    name: "Hamburg Logistics Park",
    abbreviationName: "HLP",
    zip: "20095",
    address: "Hafenallee 88",
    city: "Hamburg",
    country: "Germany",
  },
];

export const plants: Plant[] = [
  {
    id: "plant-1",
    siteId: "site-1",
    name: "Assembly Line Alpha",
    code: "ALA-001",
    level1: "Berlin Manufacturing Hub",
    zip: "10115",
    address: "Industriestraße 12, Halle A",
    city: "Berlin",
    country: "Germany",
  },
  {
    id: "plant-2",
    siteId: "site-1",
    name: "Welding Station Beta",
    code: "WSB-002",
    level1: "Berlin Manufacturing Hub",
    zip: "10115",
    address: "Industriestraße 12, Halle B",
    city: "Berlin",
    country: "Germany",
  },
  {
    id: "plant-3",
    siteId: "site-2",
    name: "Paint Shop Gamma",
    code: "PSG-003",
    level1: "Munich Engineering Center",
    zip: "80331",
    address: "Technikweg 5, Gebäude 3",
    city: "Munich",
    country: "Germany",
  },
  {
    id: "plant-4",
    siteId: "site-3",
    name: "Quality Control Delta",
    code: "QCD-004",
    level1: "Hamburg Logistics Park",
    zip: "20095",
    address: "Hafenallee 88, Block D",
    city: "Hamburg",
    country: "Germany",
  },
];

export const closedProtocols: ClosedProtocol[] = [
  {
    id: "1",
    siteId: "site-1",
    plantId: "plant-1",
    level1: "Berlin Manufacturing Hub",
    name: "Monthly Safety Inspection - January",
    basedOn: "Safety Protocol Template v2.1",
    date: "2024-01-31",
    owner: "inspector.mueller",
    status: "closed",
  },
  {
    id: "2",
    siteId: "site-1",
    plantId: "plant-2",
    level1: "Berlin Manufacturing Hub",
    name: "Equipment Calibration Report - Q1",
    basedOn: "Calibration Standard ISO 17025",
    date: "2024-03-31",
    owner: "tech.schmidt",
    status: "closed",
  },
  {
    id: "3",
    siteId: "site-2",
    plantId: "plant-3",
    level1: "Munich Engineering Center",
    name: "Paint Quality Audit - February",
    basedOn: "Paint Quality Standard DIN 55633",
    date: "2024-02-28",
    owner: "auditor.weber",
    status: "closed",
  },
  {
    id: "4",
    siteId: "site-3",
    plantId: "plant-4",
    level1: "Hamburg Logistics Park",
    name: "Fire Safety Drill Report",
    basedOn: "Fire Safety Regulation ASR A2.2",
    date: "2024-04-15",
    owner: "safety.fischer",
    status: "closed",
  },
  {
    id: "5",
    siteId: "site-1",
    plantId: "plant-1",
    level1: "Berlin Manufacturing Hub",
    name: "Electrical Systems Inspection - March",
    basedOn: "Electrical Safety Standard DIN VDE 0105",
    date: "2024-03-20",
    owner: "inspector.mueller",
    status: "closed",
  },
];
